PROGRAM Test_Driver

! CUBGCV TEST DRIVER
 
! Code converted using TO_F90 by Alan Miller
! Date: 2002-06-04  Time: 15:44:46
 
! ------------------

! AUTHOR          - M.F.HUTCHINSON
!                   CSIRO DIVISION OF WATER AND LAND RESOURCES
!                   GPO BOX 1666
!                   CANBERRA ACT 2601
!                   AUSTRALIA

! LATEST REVISION - 7 AUGUST 1986

! COMPUTER        - VAX/DOUBLE

! USAGE           - MAIN PROGRAM

! REQUIRED ROUTINES - CUBGCV, SPINT1, SPFIT1, SPCOF1, SPERR1, GGRAND

! REMARKS   USES SUBROUTINE CUBGCV TO FIT A CUBIC SMOOTHING SPLINE
!           TO 50 DATA POINTS WHICH ARE GENERATED BY ADDING A RANDOM
!           VARIABLE WITH UNIFORM DENSITY IN THE INTERVAL [-0.3,0.3]
!           TO 50 POINTS SAMPLED FROM THE CURVE  Y=SIN(3*PI*X/2).
!           RANDOM DEVIATES IN THE INTERVAL [0,1] ARE GENERATED BY THE
!           DOUBLE PRECISION FUNCTION GGRAND (SIMILAR TO IMSL FUNCTION
!           GGUBFS).  THE ABSCISSAE ARE UNEQUALLY SPACED IN [0,1].

!           POINT STANDARD ERROR ESTIMATES ARE RETURNED IN SE BY
!           SETTING JOB=1.  THE ERROR VARIANCE ESTIMATE IS RETURNED
!           IN VAR.  IT COMPARES FAVOURABLY WITH THE TRUE VALUE OF 0.03.
!           SUMMARY STATISTICS FROM THE ARRAY WK ARE WRITTEN TO
!           UNIT 6.  DATA VALUES AND FITTED VALUES WITH ESTIMATED
!           STANDARD ERRORS ARE ALSO WRITTEN TO UNIT 6.

USE Cubic_Spline_GCV
IMPLICIT NONE

INTEGER, PARAMETER  :: n = 50, ic = 49

INTEGER    :: i, job, ier
REAL (dp)  :: x(n), f(n), y(n), df(n), c(ic,3), wk(7*(n+2)), var, se(n)
REAL (dp)  :: dseed, randno

!---INITIALIZE---
dseed = 1.2345D4
job = 1
var = -1.0D0

!---CALCULATE DATA POINTS---
DO  i = 1, n
  CALL ggrand(dseed, randno)
  x(i) = (i-0.5) / n + (2.0*randno - 1.0) / (3.0*n)
  CALL ggrand(dseed, randno)
  f(i) = SIN(4.71238*x(i)) + (2.0*randno - 1.0) * 0.3
  df(i) = 1.0D0
END DO

!---FIT CUBIC SPLINE---
CALL cubgcv(x, f, df, n, y, c, ic, var, job, se, wk, ier)

!---WRITE OUT RESULTS---
WRITE (6,5000)
WRITE (6,5100) ier, var, wk(3), wk(4), wk(2)
WRITE (6,5200)
DO  i = 1, n - 1
  WRITE (6,5300) i, x(i), f(i), y(i), se(i), c(i,1:3)
END DO
WRITE (6,5300) n, x(n), f(n), y(n), se(n)
STOP

5000 FORMAT (' CUBGCV TEST DRIVER RESULTS:')
5100 FORMAT (/' IER =',i4/ ' VAR =', f7.4/  &
              ' GENERALIZED CROSS VALIDATION =', f7.4/  &
              ' MEAN SQUARE RESIDUAL         =', f7.4/  &
              ' RESIDUAL DEGREES OF FREEDOM  =', f7.2)
5200 FORMAT (/' INPUT DATA                 OUTPUT RESULTS'//  &
              '   I    X(I)    F(I)          Y(I)   SE(I)',  &
              '   C(I,1)      C(I,2)      C(I,3)')
5300 FORMAT (i4, 2F8.4, '      ', 2F8.4, 3g12.4)


CONTAINS


SUBROUTINE ggrand(dseed, fn_val)

! REAL (dp) UNIFORM RANDOM NUMBER GENERATOR

! CONSTANTS: A = 7**5
!            B = 2**31 - 1
!            C = 2**31

! REFERENCE: IMSL MANUAL, CHAPTER G - GENERATION AND TESTING OF RANDOM NUMBERS

!---SPECIFICATIONS FOR ARGUMENTS---

REAL (dp), INTENT(IN OUT)  :: dseed
REAL (dp), INTENT(OUT)     :: fn_val

!---SPECIFICATIONS FOR LOCAL VARIABLES---
REAL (dp)             :: s
REAL (dp), PARAMETER  :: a = 16807.0D0, b = 2147483647.0D0, c = 2147483648.0D0

s = dseed
s = MOD(a*s, b)
fn_val = s / c
dseed  = s
RETURN
END SUBROUTINE ggrand

END PROGRAM Test_Driver

